apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deploy
  labels:
    app: health
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name: healthcontainer
        image: kondetimounika/healthcare:1.0
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: healthservice
  labels:
    app: health
spec:
  selector:
    app: health

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8089
    targetPort: 8089
