apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  selector:
    matchLabels:
      app: healthcare
  replicas: 3
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcontainer
        image: arshiya13/healthcare
        imagePullPolicy: Always
        ports:
        - name: healthcare
          containerPort: 8082
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: healthservice
  labels:
    app: healthcare
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 8082
  selector:
    app: healthcare
